services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
